onflow/fcl-discovery

components/Headers/Header.js, hooks/useFCL.js
Addresses: https://github.com/onflow/fcl-discovery/issues/39
=> Version check fix

README.md
Addresses: https://github.com/onflow/fcl-discovery/issues/42
=> DOCS - add documentation about how to add a wallet to discovery

.gitignore, helpers/constants.js, package-lock.json, package.json, pages/api/[...slug].js
Addresses: https://github.com/onflow/fcl-discovery/issues/46
=> Chore: Add error monitoring

hooks/useFCL.js
Addresses: https://github.com/onflow/fcl-discovery/issues/50
=> Feature: Get extensions from new client config

package-lock.json, package.json
Addresses: https://github.com/onflow/fcl-discovery/issues/52
=> Chore: Upgrade FCL to 1.0

components/Discovery.js, helpers/constants.js, next.config.js, package-lock.json, package.json
Addresses: https://github.com/onflow/fcl-discovery/issues/55, https://github.com/onflow/fcl-discovery/issues/57
=> Chore: Upgrades and Bug Fix

helpers/constants.js
This reverts commit 65ec6265203f8dcfe3e75133a892b1fe99b63b96.
=> Revert "Change extension supported version to 1.0.0"

README.md, components/Discovery.js, components/ServiceCard.js, data/metadata.json, docs/service-fields.md, helpers/__tests__/services.test.js, helpers/__tests__/userAgent.js, helpers/constants.js, helpers/metadata.js, helpers/services.js, helpers/strings.js, helpers/userAgent.js, helpers/window.js, pages/_app.js, pages/api/[...slug].js
Addresses: https://github.com/onflow/fcl-discovery/issues/66
=> Show Uninstalled Extensions

hooks/useLocalStorage.js
Addresses: https://github.com/onflow/fcl-discovery/issues/76
=> Bug: Fix incognito local storage error

hooks/useLocalStorage.js
Addresses: https://github.com/onflow/fcl-discovery/issues/76
=> Bug: Check if local storage is available

components/Headers/__tests__/AppHeader.test.js, components/Headers/__tests__/Header.test.js, components/__tests__/Explainer.test.js, package-lock.json
Addresses: https://github.com/onflow/fcl-discovery/issues/91
=> Fix build: update tests and update package lock

data/services.json
Addresses: https://github.com/onflow/fcl-discovery/issues/95
=> Update blocto service on testnet

README.md, helpers/__tests__/services.test.js, helpers/services.js, helpers/version.js, helpers/version.ts, hooks/useFCL.js, next-env.d.ts, package-lock.json, package.json, tsconfig.json, types/index.ts, types/services.ts
Tested against old versions and found bug.
Also addresses: https://github.com/onflow/fcl-discovery/issues/104
=> Fix pipe version finder

components/Discovery.js
Addresses: https://github.com/onflow/fcl-discovery/issues/110
=> Increase scroll space when wallet list is long

helpers/servicePipes.js, helpers/services.js, tsconfig.json
Addresses: https://github.com/onflow/fcl-discovery/issues/113
=> Fix extensions always going to install link

helpers/servicePipes.js
Addresses: https://github.com/onflow/fcl-discovery/issues/115
=> Filter services by platform in new pipeline

pages/api/[...slug].js
Addresses: https://github.com/onflow/fcl-discovery/issues/117
=> Fix: account for both versions from FCL on API

components/ServiceCard.js
Addresses: https://github.com/onflow/fcl-discovery/issues/81
=> Reduce service card height

README.md, helpers/__tests__/paths.test.js, helpers/constants.js
Addresses: https://github.com/onflow/fcl-discovery/issues/131
=> Feature: create explicit mainnet path

data/services.json, helpers/__tests__/paths.test.js, helpers/constants.js
Addresses: https://github.com/onflow/fcl-discovery/issues/137
=> Feature: create sandboxnet

data/metadata.json, data/services.json
The wallet has 2 versions:
- [Flipper](https://chrome.google.com/webstore/detail/flipper/lmmpaefggfcmnoddemmgdppddppnmhek) which runs on Mainnet
- [Flipper Developer](https://chrome.google.com/webstore/detail/flipper/nkjhfapihbllbhhneonipcinhdlcmfgn) which runs on Testnet 
_Note: Flipper Developer is pending Chrome store approval_
=> Add Flipper wallet

components/ServiceCard.js
Addresses: https://github.com/onflow/fcl-discovery/issues/141
=> Fix: last used background

helpers/constants.js, helpers/servicePipes.js, helpers/services.js
Addresses: https://github.com/onflow/fcl-discovery/issues/145 (lintfix also ran on files)
=> Fix: only show default services before specified version

hooks/useFCL.js, pages/index.js
Addresses: https://github.com/onflow/fcl-discovery/issues/132
-----
Error was making it so the information was not showing if no path and just on index. Fix for this makes it appear again.
=> Fix: index page for more information missing

data/features.json, data/metadata.json
Adds account-linking feature and removes others
=> Adds account-linking feature and removes others

data/metadata.json, data/services.json
Changing the Flipper service attributes as our rebranded wallet (Shadow) is coming out soon.
=> Changing the flipper service objects to match it’s new branding

package-lock.json, package.json
=> Update to NextJS v14
